// SPDX-FileCopyrightText: 2020 Foundation Devices, Inc. <hello@foundationdevices.com>
// SPDX-License-Identifier: GPL-3.0-or-later
//
//
// Autogenerated - Do not edit!
//

#include <stdint.h>

typedef struct _Image {
    int16_t  width;
    int16_t  height;
    int16_t  byte_width;
    uint8_t* data;
} Image;

extern Image splash_img;
