// SPDX-FileCopyrightText: 2020 Foundation Devices, Inc. <hello@foundationdevices.com>
// SPDX-License-Identifier: GPL-3.0-or-later
//
//
// Autogenerated - Do not edit!
//

#include <stdint.h>

typedef struct _Image {
    int16_t  width;
    int16_t  height;
    int16_t  byte_width;
    uint8_t* data;
} Image;

extern Image busybar1_img;
extern Image busybar2_img;
extern Image busybar3_img;
extern Image busybar4_img;
extern Image busybar5_img;
extern Image busybar6_img;
extern Image busybar7_img;
