# SPDX-FileCopyrightText: 2021 Foundation Devices, Inc. <hello@foundationdevices.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Build all Python graphics and copy files to main source folder
build:
    make
    cp graphics.py ../../modules/
