# SPDX-FileCopyrightText: 2020 Foundation Devices, Inc. <hello@foundationdevices.com>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# SPDX-FileCopyrightText: 2018 Coinkite, Inc. <coldcardwallet.com>
# SPDX-License-Identifier: GPL-3.0-only
#
# (c) Copyright 2018 by Coinkite Inc. This file is part of Coldcard <coldcardwallet.com>
# and is covered by GPLv3 license found in COPYING.

all: graphics.py
	
SOURCES = $(wildcard *.txt) $(wildcard *.png)

graphics.py: Makefile $(SOURCES) build.py
	python3 build.py $(SOURCES)

up: all
	(cd ../shared; make up)
